debug_level = 2

num_species = 2

ion_mass = 1.0

max_ptc_num = 1_000_000
max_ph_num = 1_000
ptc_buffer_size = 500_000
ptc_segment_size = 100_000
max_tracked_num = 1_000_000

dt = 1.0e-3

q_e = 1.0

current_smoothing = 1

use_pml = true

### Simulation life time
max_steps = 5000

fld_output_interval = 50

ptc_output_interval = 50

tracked_fraction = 0.1

snapshot_interval = 0 # disable snapshots

sort_interval = 11

### Grid parameters
# Number of grid points in each direction, excluding guard cells. This should be
# a multiple of at least 32.
N = [256, 64]

nodes = [2, 4]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard. Minimum 2 is required!
guard = [2, 2]

# Lower limit of the coordinate
lower = [0.0, 0.0]

# Size of the box in each dimension
size = [2.0, 0.5]

# Whether boundaries are periodic
periodic_boundary = [true, true]

# Whether to use PML damping
damping_boundary = [false, false, false, false]

# Length of the PML layer
pml_length = 10

# Field output downsample factor
downsample = 4

# Parameters for Two Stream setup
rho_b = 100.0

rho_0 = 100.0

p0 = 0.1

multiplicity = 50
