log_level = 0

num_species = 2

ion_mass = 1.0

max_ptc_num = 100_000_000
ptc_segment_size = 10_000_000
max_ph_num = 100_000_000
ph_segment_size = 10_000_000
ptc_buffer_size = 1_000_000
ph_buffer_size = 1_000_000

dt = 7.0e-3

q_e = 1.0

use_implicit = false

Bp = 1.0e4

B_Q = 1.0e5

Rpc = 1.0

R_star = 5.48
#R_star = 10.0

current_smoothing = 1

e0 = 1.0e-3

nc = 0.1

zeta = 30.0

N_inject = 1

emit_photons = true

produce_pairs = true

### Simulation life time
max_steps = 5001

fld_output_interval = 100

ptc_output_interval = 500

snapshot_interval = 0 # disable snapshots

sort_interval = 23

### Grid parameters
# Number of grid points in each direction, excluding guard cells. This should be
# a multiple of at least 32.
N = [192, 192, 256]

nodes = [2, 2, 1]

# Number of guard cells on each end. Effective number of cells per dimension
# will be N + 2*guard. Minimum 2 is required!
guard = [2, 2, 2]

# Lower limit of the coordinate
lower = [-2.5, -2.5, 0.0]

# Size of the box in each dimension
size = [5.0, 5.0, 5.0]

# Whether boundaries are periodic
periodic_boundary = [false, false, false]

# Whether to use PML damping
damping_boundary = [true, true, true, true, false, true]

# Length of the PML layer
pml_length = 12

# Field output downsample factor
downsample = 2

output_dir = "/home/alex/nvme/Data/Polar Cap/data/"
